// Code generated by go generate; DO NOT EDIT.
// +build linux_bpf

package runtime

var RuntimeSecurity = NewRuntimeAsset("runtime-security.c", "a794c40c098ae0f6e05256c7d1f2d20ab79523a467462a6b0c3b893234680688")
